- hosts: localhost
  connection: local
  tasks:
    - name: Import VPC variable
      include_vars: vprostacksetup

    - name: Import VPC output variable
      include_vars: output_var

    - name: variable file
      include_vars: vpc_setup

    - name: create vpro ec2 key
      ec2_key:
        name: vprokey
        region: "{{region}}"
      register: vprokey_out

    - name: save the private key
      copy:
        content: "{{vprokey_out.key.private_key}}"
        dest: ./loginkey_vpro.pem
        mode: 0600
      when: vprokey_out.changed
